### ISSUE TITLE
vs2013编译不通过

### ISSUE THREAD

**Issue by kxjhcs** [qicosmos/Kapok#10]
vs2013编译不通过

**Comment by qicosmos** [comment]
可以把编译错误发上来吗？

**Comment by kxjhcs** [comment]
ui\third-party\kapok\kapok\jsonutil.hpp : warning C4819: 该文件包含不能在当前代码页(936)中表示的字符。请将该文件保存为 Unicode 格式以防止数据丢失
1>ui\third-party\kapok\kapok\jsonutil.hpp(201): error C2899: 不能在模板声明之外使用类型名称
1>ui\third-party\kapok\kapok\jsonutil.hpp(201): error C2065: “T”: 未声明的标识符
1>ui\third-party\kapok\kapok\jsonutil.hpp(201): error C2923: “is_pointer_ext”: 对于参数“T”，“T”不是有效的 模板 类型变量
1>ui\third-party\kapok\kapok\jsonutil.hpp(201): error C2955: “is_pointer_ext”: 使用 类 模板 需要 模板 参数列表
1>          ui\third-party\kapok\kapok\traits.hpp(116) : 参见“is_pointer_ext”的声明
1>ui\third-party\kapok\kapok\jsonutil.hpp(201): error C2146: 语法错误: 缺少“;”(在标识符“WriteValue”的前面)
1>ui\third-party\kapok\kapok\jsonutil.hpp(201): error C2061: 语法错误: 标识符“T”
1>ui\third-party\kapok\kapok\jsonutil.hpp(202): error C4430: 缺少类型说明符 - 假定为 int。注意:  C++ 不支持默认 int
1>ui\third-party\kapok\kapok\jsonutil.hpp(204): warning C4183: “WriteValue”:  缺少返回类型；假定为返回“int”的成员函数
1>ui\third-party\kapok\kapok\jsonutil.hpp(86): error C2065: “m_doc”: 未声明的标识符
1>ui\third-party\kapok\kapok\jsonutil.hpp(86): error C2228: “.Parse”的左边必须有类/结构/联合
1>          类型是“unknown-type”
1>ui\third-party\kapok\kapok\jsonutil.hpp(91): error C2065: “m_doc”: 未声明的标识符

**Comment by qicosmos** [comment]
应该是编码的问题，之前测了vs2013下编译没问题，我后面再看看。

**Comment by qicosmos** [comment]
从github上clone代码，然后新建vs2013/2015工程，添加头文件引用，编译都没问题，仅仅只有一个unicode编码的告警，并没有编译错误。
按照我说的再试试吧。

**Comment by kxjhcs** [comment]
好的，谢谢
