### ISSUE TITLE
查找遍历json

### ISSUE THREAD

**Issue by zhangyuchun** [qicosmos/Kapok#18]
```
template<size_t N = 0, typename T>
auto ReadValue(T&& t, Value& val, std::false_type bo) -> std::enable_if_t<is_tuple<T>::value>
{
    assert(!val.IsArray());
    decltype(auto) tuple_elem = std::get<N>(t);
    auto it = val.MemberBegin() + N;
    assert(0 == std::strcmp(tuple_elem.first, it->name.GetString()));
    ReadObject(tuple_elem, (Value&)(it->value), bo);
}
```

这里tuple跟json的顺序相关了。为什么不遍历查找匹配？

**Comment by qicosmos** [comment]
这个函数只是读取tuple中的第N的元素, 遍历tuple的函数是没有 size_t N的模板函数.
另外没看明白你的意思，再说清楚一点吧。

**Comment by qicosmos** [comment]
“为什么不遍历查找匹配？”， 这句具体是指什么？

**Comment by zhangyuchun** [comment]
```
template<size_t N = 0, typename T>
auto ReadValue(T&& t, Value& val, std::false_type bo) -> std::enable_if_t<is_tuple<T>::value>
{


    assert(!val.IsArray());
    decltype(auto) tuple_elem = std::get<N>(t);
    auto it = val.MemberBegin() ;
    while (it != val.MemberEnd())
    {
        if (std::strcmp(it->name.GetString(), tuple_elem.first) == 0)
        {
            ReadObject(tuple_elem, (Value &)(it->value), bo);
            break;
        }
        it++;
    }
}
```

如果改成类似这样查找匹配，就会去除tuple元素的顺序和json字段的顺序关系，就不会有断言情况发生。
是因为性能关系，不这样做吗？

**Comment by qicosmos** [comment]
@zhangyuchun 这样做不行的，你需要考虑普通的tuple，普通的tuple是没有pair的，要通用。

**Comment by Madokakaroto** [comment]
@zhangyuchun 你好。
1. ReadValue的这模板函数的第三个参数是有std::false_type和std::true_type两个重载版本的。
2. std::false_type的重载解析版本是处理普通的tuple；而std::true_type的重载解析版本是处理struct的Meta函数映射来的tuple类型，里面通常是一个pair包装的一对key-value二元组。
3. 我们还是倾向遍历tuple来驱动反序列化，你可以发现RedTuple稍作修改，使用递归模板或者一些其他的静态方法展开Tuple的反序列化，这个比使用控制循环语句的性能要高，并且是编译期的。

**Comment by zhangyuchun** [comment]
@IndignantAngel 你好。
1 std::false_type是处理Meta的。std::true_type是处理普通tuple。说反了。
2 如果不循环查找，如果json顺序和meta顺序不一样，就会有问题。但循环查找又会影响性能。

> struct test_json
> {
>   int a;
>   std::string b;
> 
>   META(a, b);
> };
> 
> void test_myjosn()
> {
> 
> ```
>   std::string str = "{\"b\":\"test\" , \"a\" :1}";
>   test_json json;
>   DeSerializer ds;
>   ds.Parse(str);
>   ds.Deserialize(json);
> ```
> 
> }

**Comment by Madokakaroto** [comment]
@zhangyuchun 你好。
感谢你的提醒，我们一开始的设计是依赖顺序的。但是你的提醒让我们觉得不是很妥当，毕竟对结构体的序列化中加入了key，那么就应该顺序无关。不过，你给出的代码，示例的行为依然是不推荐的，请不要自行编写json串，或者篡改由序列化模块生成的json串，这样很可能会招致错误的发生。代码我们已经修改，会尽快提交。再次感谢。
