### ISSUE TITLE
multiple definition of Int2String

### ISSUE THREAD

**Issue by wzcsoft** [qicosmos/Kapok#8]
举个例子，如果Kapok.hpp分别被a.cpp和b.cpp include，a.cpp b.cpp被分别编译成a.o b.o，然后这两个.o文件被link程一个可执行文件，那么link的时候会出现multiple definition of Int2String这个错误。 目前我用一个山寨的方法 const char\* Int2String[]  ==> static const char\* Int2String[]来解决这个问题

**Comment by qicosmos** [comment]
恩，谢谢指出，加个static就好了。已修复。
